--DROP table STUDENT_LAPTOP;
DROP table LAPTOP_STUDENT;
DROP table LAPTOP;
DROP table STUDENT;

SELECT * FROM STUDENT;
SELECT * FROM LAPTOP;
SELECT * FROM LAPTOP_STUDENT;
--SELECT * FROM STUDENT_LAPTOP; /* This table has been not been created because of the use of mappedBy property*/






--------------------------------------------------------------------------------------------------------------------------------
/*CREATE TABLE "BOOKS" 
   (	"BOOK_ID" VARCHAR2(6 CHAR), 
	"BOOK_TITLE" VARCHAR2(150 BYTE), 
	"BOOK_COST" NUMBER(20,2), 
	"BOOK_TYPE" VARCHAR2(2 CHAR), 
	"PUBL_ID" NUMBER(3,0), 
	"BOOK_EDITION" VARCHAR2(10 CHAR), 
	"BOOK_DISCOUNT" NUMBER(5,2), 
	"ISBN" VARCHAR2(15 BYTE), 
	"PUBL_DATE" DATE
   ) ;
   
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0056','DataBase Systems',935.27,'DB',11,'Fifth',10,'978-8131716250',to_date('01-MAY-08','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0059','Database Systems',1003.67,'DB',11,'Eighth',10,'978-8185015583',to_date('01-JAN-02','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0063','The Java TM Programming Language',425,'PR',11,'Third',10,'978-8131702215',to_date('01-JAN-08','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0067','The Java TM EE5 Tutorial',725,'PR',11,null,18,'978-8131714928',to_date('03-NOV-06','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0071','The Complete Reference HTML & XHTML',540,'PR',15,'Fourth',16,'978-0070701946',to_date('08-MAR-10','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0075','Inside Microsoft  Office Sharepoint  Server 2007',699,'PR',17,null,15,'978-9350041666',to_date('16-MAY-07','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0081','MCITP  Microsoft Certified IT Professional 5-in-1 Study System',699,'PR',7,null,15,'978-9350040102',to_date('01-JAN-11','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0087','UNIX System Administrator''s Bible',450,'OS',5,null,null,'978-0764531620',to_date('14-JUL-98','DD-MON-RR'));
Insert into BOOKS (BOOK_ID,BOOK_TITLE,BOOK_COST,BOOK_TYPE,PUBL_ID,BOOK_EDITION,BOOK_DISCOUNT,ISBN,PUBL_DATE) values ('B0090','UNIX Power Tools',750,'PR',14,'Third',20,'978-0679790730',to_date('08-OCT-02','DD-MON-RR'));
*/




